MCU = RP2040
BOOTLOADER = rp2040

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

OLED_ENABLE = yes
LTO_ENABLE = yes
I2C_DRIVER_REQUIRED = yes

RGBLIGHT_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes

WS2812_DRIVER = vendor
OPT_DEFS += -DWS2812_DI_PIN=GP3